apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-db
  namespace: default
  labels:
    app: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant-container
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
          name: http-api
        - containerPort: 6334
          name: grpc-api
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 6333
    targetPort: 6333
    name: http
  - port: 6334
    targetPort: 6334
    name: grpc
  selector:
    app: qdrant
